<?php
  define( 'FRAMEWORK_DBI', false );
  define( 'FRAMEWORK_SQLHOST', 'localhost' );
  define( 'FRAMEWORK_SQLUSER', '' );
  define( 'FRAMEWORK_SQLDB', '' );
  define( 'FRAMEWORK_SQLPW', '' );
  define( 'FRAMEWORK_SESSIONMGR', false );
  define( 'FRAMEWORK_SESSIONTIMEOUTANON', 300 );
  define( 'FRAMEWORK_SESSIONTIMEOUTUSER', 3600 );
  define( 'FRAMEWORK_AUTHMETHOD', 'auth_mysql_pwauth' );
  define( 'FRAMEWORK_FORCELOGIN', 'Login' );
  define( 'FRAMEWORK_MULTILANG', false );
  define( 'FRAMEWORK_DEFAULTLANG', 'en' );
  define( 'FRAMEWORK_TITLE', '' );
  define( 'FRAMEWORK_AUTHOR', '' );
  define( 'FRAMEWORK_COMPANY', '' );
  define( 'FRAMEWORK_COPYRIGHT', 'copyright by . Publishing and redistribution only with permission.' );
  define( 'FRAMEWORK_SUBJECT', 'Industrial' );
  define( 'FRAMWORKD_COVERAGE', 'global' );
  define( 'FRAMEWORK_AUDIENCE', 'all' );
  define( 'FRAMEWORK_EXPIRES', '0' );
  define( 'FRAMEWORK_ROBOTS', 'index,follow' );
  define( 'FRAMEWORK_REVISIT', '5 days' );
  define( 'FRAMEWORK_CACHE', 'no-cache' );
  define( 'FRAMEWORK_TOP_LINK', 'Home' );
  define( 'FRAMEWORK_COPYRIGHT_LINK', 'Imprint' );
  define( 'FRAMEWORK_ROOT', '/' );
#  define( 'FRAMEWORK_DEBUG', 0 );
  define( 'FRAMEWORK_DEBUG', E_ALL );
  define( 'FRAMEWORK_PWAUTH', '/bin/pwauth' );
